# Generated by Django 5.1.2 on 2024-11-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
