# Generated by Django 5.1.2 on 2024-11-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='review',
            name='human_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='model_sentiment',
            field=models.CharField(default='Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
