# Generated by Django 5.1.2 on 2024-11-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_review_sentiment_review_human_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confidence',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
