# Generated by Django 5.1.2 on 2024-11-22 20:21

from django.db import migrations


def populate_ml_models(apps, schema_editor):
    MLModel = apps.get_model('your_app_name', 'MLModel')
    MLModel.objects.bulk_create([
        MLModel(
            file_name="lstm_model.h5",
            created_at="2024-11-20T17:47:36.338000Z",
            accuracy=0.82,
            precision=0.66,
            recall=0.71,
            f1_score=0.85,
            is_active=False
        ),
        MLModel(
            file_name="lstm_model_balanced.h5",
            created_at="2024-11-21T17:47:36.338000Z",
            accuracy=0.75,
            precision=0.75,
            recall=0.75,
            f1_score=0.75,
            is_active=True
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mlmodel_review_linked_ml_model'),
    ]

    operations = [
        migrations.RunPython(populate_ml_models),
    ]
